//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSTK_MoneyLover.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMoneyLoverEntities : DbContext
    {
        public DbMoneyLoverEntities()
            : base("name=DbMoneyLoverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<PassBook> PassBooks { get; set; }
        public virtual DbSet<RoleAdmin> RoleAdmins { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<UserAdmin> UserAdmins { get; set; }
        public virtual DbSet<Withdraw> Withdraws { get; set; }
        public virtual DbSet<Deposit> Deposits { get; set; }
        public virtual DbSet<PassbookDetail> PassbookDetails { get; set; }
        public virtual DbSet<InterestRate> InterestRates { get; set; }
    }
}
