//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSTK_MoneyLover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int Id { get; set; }
        public int PassBookId { get; set; }
        public string Acronym { get; set; }
        public System.DateTime DepositDate { get; set; }
        public decimal Amount { get; set; }
        public int Status { get; set; }
    
        public virtual PassBook PassBook { get; set; }
    }
}
