//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSTK_MoneyLover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestRate
    {
        public int Id { get; set; }
        public int BankId { get; set; }
        public int TermId { get; set; }
        public string Acronym { get; set; }
        public double Rate { get; set; }
        public int Status { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Term Term { get; set; }
    }
}
