//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSTK_MoneyLover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PassBook()
        {
            this.Withdraws = new HashSet<Withdraw>();
            this.Deposits = new HashSet<Deposit>();
            this.PassbookDetails = new HashSet<PassbookDetail>();
        }
    
        public int Id { get; set; }
        public int BankId { get; set; }
        public int TermId { get; set; }
        public int CustomerId { get; set; }
        public string Acronym { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime OpenDate { get; set; }
        public int InterestPayment { get; set; }
        public Nullable<int> TermEnd { get; set; }
        public int Status { get; set; }
        public decimal Principal { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public double InterestRate { get; set; }
        public double DemandInterestRate { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Term Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Withdraw> Withdraws { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deposit> Deposits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassbookDetail> PassbookDetails { get; set; }
    }
}
