//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSTK_MoneyLover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassbookDetail
    {
        public int Id { get; set; }
        public int PassbookId { get; set; }
        public string Action { get; set; }
        public System.DateTime ActionDate { get; set; }
        public decimal Balance { get; set; }
        public decimal Amount { get; set; }
        public decimal Surplus { get; set; }
        public int Status { get; set; }
    
        public virtual PassBook PassBook { get; set; }
    }
}
