//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSTK_MoneyLover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleAdmin()
        {
            this.UserAdmins = new HashSet<UserAdmin>();
        }
    
        public int Id { get; set; }
        public string Acronym { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAdmin> UserAdmins { get; set; }
    }
}
