//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSTK_MoneyLover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdmin
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public string Acronym { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Encrypted { get; set; }
        public int Status { get; set; }
    
        public virtual RoleAdmin RoleAdmin { get; set; }
    }
}
